### ISSUE TITLE
auto_rxn throws an error when freshly installed

### ISSUE THREAD

**Issue by ukurumbail** [uw-madison-chem-shops/auto_rxn#49]
Error regarding happi thrown when auto_rxn is first installed and ran. Perhaps the 'installation' could include a quick explanation of how to create a happi database?

`(base) C:\Users\herma\Documents\scripts>auto-rxn
Usage: auto-rxn [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  edit-limits
  list-devices
  run

(base) C:\Users\herma\Documents\scripts>auto-rxn list-devices
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\happi\backends\json_db.py", line 78, in _load_or_initialize
    self._load_cache = self.load()
  File "C:\ProgramData\anaconda3\lib\site-packages\happi\backends\json_db.py", line 117, in load
    with open(self.path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\herma\\AppData\\Local\\happi\\happi\\db.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Scripts\auto-rxn-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\anaconda3\lib\site-packages\auto_rxn\__main__.py", line 46, in _list_devices
    for name, result in happi_client.items():
  File "C:\ProgramData\anaconda3\lib\_collections_abc.py", line 910, in __iter__
    for key in self._mapping:
  File "C:\ProgramData\anaconda3\lib\site-packages\happi\client.py", line 499, in __iter__
    for info in self.backend.find({}):
  File "C:\ProgramData\anaconda3\lib\site-packages\happi\backends\json_db.py", line 209, in find
    yield from self._iterative_compare(comparison)
  File "C:\ProgramData\anaconda3\lib\site-packages\happi\backends\json_db.py", line 177, in _iterative_compare
    db = self._load_or_initialize()
  File "C:\ProgramData\anaconda3\lib\site-packages\happi\backends\json_db.py", line 81, in _load_or_initialize
    self.initialize()
  File "C:\ProgramData\anaconda3\lib\site-packages\happi\backends\json_db.py", line 113, in initialize
    self.store({})
  File "C:\ProgramData\anaconda3\lib\site-packages\happi\backends\json_db.py", line 142, in store
    with open(temp_path, 'w') as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\herma\\AppData\\Local\\happi\\happi\\.herma_1693439465_575a2ae6_db.json'`

**Comment by untzag** [comment]
Hi @ukurumbail I'd really appreciate if you could write down your fresh learnings about install to the docs. Since you struggled you'll probably know what the pain points are.

We could try to make auto rxn give better hints too...
